# Generated by Django 5.0.2 on 2024-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_department_description_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth'), ('9', 'Ninth'), ('10', 'Tenth')], max_length=3),
        ),
    ]
