# Generated by Django 5.0.2 on 2024-03-21 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('tag', models.CharField(choices=[('core', 'Core'), ('hasmed', 'Hasmed Elective'), ('minor', 'Minor'), ('honors', 'Honors'), ('dept_elective', 'Department Elective')], max_length=20)),
                ('credits', models.FloatField()),
                ('semester', models.CharField(choices=[('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10)),
                ('years', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('semester_type', models.CharField(choices=[('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_offered', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('rollnum', models.CharField(max_length=10, unique=True)),
                ('semester', models.CharField(choices=[('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10)),
                ('degree', models.CharField(default='B.Tech', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.department')),
                ('groups', models.ManyToManyField(default=1, related_name='custom_user_set', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(default=1, related_name='custom_user_set', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('inprogress', 'In Progress'), ('plan', 'Planned')], default='completed', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taken', to='courses.courseoffered')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taken', to='courses.student', to_field='rollnum')),
            ],
        ),
    ]
