# Generated by Django 5.0.2 on 2024-03-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taken', to='courses.user', to_field='rollnum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rollnum',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
