# Generated by Django 5.0.2 on 2024-03-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0002_department_remove_course_semester_coursetaken_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='coursetaken',
            name='year',
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_offered', to='courses.course')),
            ],
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taken', to='courses.courseoffered'),
        ),
    ]
