# Generated by Django 5.0.2 on 2024-03-21 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0002_user_id_alter_coursetaken_student_alter_user_rollnum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('rollnum', models.CharField(max_length=10, unique=True)),
                ('semester', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.department')),
                ('groups', models.ManyToManyField(default=1, related_name='custom_user_set', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(default=1, related_name='custom_user_set', to='auth.permission')),
            ],
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taken', to='courses.student', to_field='rollnum'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
