# Generated by Django 5.0.2 on 2024-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetaken',
            name='study_year',
            field=models.IntegerField(),
        ),
    ]
