# Generated by Django 5.0.2 on 2024-03-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_student_user_remove_coursetaken_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffered',
            name='semester_type',
            field=models.CharField(choices=[('1', 'Autumn'), ('2', 'Spring')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='coursetaken',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taken', to='courses.user'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
