# Generated by Django 5.0.2 on 2024-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_student_alter_coursetaken_student_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='B.Tech', max_length=100),
        ),
    ]
