# Generated by Django 5.0.2 on 2024-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseoffered_semester_type_coursetaken_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffered',
            name='semester_type',
        ),
        migrations.AddField(
            model_name='course',
            name='semester_type',
            field=models.CharField(choices=[('1', 'Autumn'), ('2', 'Spring')], default='1', max_length=1),
        ),
    ]
