# Generated by Django 5.0.2 on 2024-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0005_remove_courseoffered_semester_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='semester_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='study_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(default=1, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(default=1, related_name='custom_user_set', to='auth.permission'),
        ),
    ]
