# Generated by Django 5.0.2 on 2024-03-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_years_alter_course_semester_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='semester_type',
            new_name='semester',
        ),
    ]
