# Generated by Django 5.0.2 on 2024-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_coursetaken_semester_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetaken',
            name='grade',
        ),
        migrations.AddField(
            model_name='coursetaken',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('inprogress', 'In Progress'), ('plan', 'Planned')], default='completed', max_length=10),
        ),
    ]
