# Generated by Django 5.0.2 on 2024-03-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_semester'),
        ('courses', '0009_remove_coursetaken_grade_coursetaken_status'),
    ]

    operations = [
    ]
