# Generated by Django 5.0.2 on 2024-03-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_merge_20240319_0603'),
        ('courses', '0011_alter_course_semester'),
    ]

    operations = [
    ]
