# Generated by Django 5.0.2 on 2024-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_merge_20240320_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='semester_type',
            field=models.CharField(choices=[('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10),
        ),
    ]
